# Generated by Django 5.2.15 on 2026-06-20 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('funder_type', models.CharField(choices=[('ngo', 'NGO'), ('corporate_csr', 'Corporate CSR'), ('government', 'Government'), ('individual_donor', 'Individual Donor')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('fulfilling', 'Fulfilling'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('impact_narrative', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_orders', to='funders.funderorganization')),
                ('linked_distribution_records', models.ManyToManyField(blank=True, related_name='procurement_orders', to='distributions.distributionrecord')),
                ('target_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_orders', to='distributions.school')),
            ],
        ),
    ]
