# Generated by Django 5.2.15 on 2026-06-23 00:37

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_email_login_multi_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.EmailRoleUserManager()),
            ],
        ),
    ]
