# Generated by Django 5.2.15 on 2026-06-22 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_code", models.CharField(max_length=20, unique=True)),
                (
                    "catchment_area",
                    models.CharField(
                        help_text="Community / area the agent primarily serves",
                        max_length=150,
                    ),
                ),
                (
                    "gps_home_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_home_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mobile_money_number", models.CharField(max_length=20)),
                (
                    "momo_provider",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN MoMo"),
                            ("vodafone", "Vodafone Cash"),
                            ("airteltigo", "AirtelTigo Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("native_momo", "Native MTN MoMo"),
                            ("hubtel", "Hubtel"),
                        ],
                        default="native_momo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentInventoryAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_allocated", models.PositiveIntegerField()),
                ("quantity_remaining", models.PositiveIntegerField()),
                ("allocation_date", models.DateTimeField(auto_now_add=True)),
                ("restock_requested", models.BooleanField(default=False)),
                (
                    "restock_notes",
                    models.TextField(
                        blank=True,
                        help_text="Agent's note accompanying the restock request (e.g. quantity needed, reason).",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_allocations",
                        to="agents.agent",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.inventorybatch",
                    ),
                ),
            ],
        ),
    ]
