# Generated by Django 5.2.15 on 2026-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agent_gps_home_lat_alter_agent_gps_home_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="gps_home_lat",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="gps_home_lng",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=6, null=True
            ),
        ),
    ]
