# Generated by Django 5.2.15 on 2026-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('school', 'School'), ('district', 'District'), ('national', 'National')], max_length=20)),
                ('scope_reference', models.CharField(help_text="School name / district name / 'national'", max_length=150)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('girls_reached_estimate', models.PositiveIntegerField(default=0)),
                ('pads_distributed_count', models.PositiveIntegerField(default=0)),
                ('schools_covered_count', models.PositiveIntegerField(default=0)),
                ('total_funder_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_per_girl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
