# Generated by Django 5.2.15 on 2026-06-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_code", models.CharField(max_length=30, unique=True)),
                ("production_date", models.DateField()),
                ("quantity_produced", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Production cost per unit (GHS)",
                        max_digits=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_production", "In Production"),
                            ("allocated", "Allocated"),
                            ("distributed", "Distributed"),
                            ("depleted", "Depleted"),
                        ],
                        default="in_production",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
