# Generated by Django 6.0.6 on 2026-06-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_order_payment_method_order_payment_reference_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='shop_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='community.order'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='direction',
            field=models.CharField(choices=[('outbound_payout', 'Outbound Agent Payout'), ('inbound_procurement', 'Inbound Funder Payment'), ('inbound_shop_order', 'Inbound Community Shop Payment')], max_length=30),
        ),
    ]
