# Generated by Django 5.2.15 on 2026-06-22 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("district", models.CharField(default="Kumbungu", max_length=100)),
                ("region", models.CharField(default="Northern", max_length=100)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("estimated_girls_population", models.PositiveIntegerField(default=0)),
                ("partner_organization", models.CharField(blank=True, max_length=150)),
                (
                    "poverty_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="District-level multidimensional poverty % (from GSS data)",
                        max_digits=5,
                    ),
                ),
                (
                    "distance_to_market_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "historical_absenteeism_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% of menstruating girls reporting period-related absenteeism, if known",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DistributionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("school", "School"),
                            ("community_group", "Community Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("momo", "Mobile Money"),
                            ("subsidized", "Subsidized"),
                            ("free", "Free (funded)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gps_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("gps_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="Reverse-geocoded place name for gps_lat/gps_lng (e.g. 'Kumbungu, Northern Region'). Best-effort, set client-side at capture time -- coordinates remain the source of truth.",
                        max_length=255,
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        help_text="Cloudinary URL of proof-of-distribution photo"
                    ),
                ),
                (
                    "photo_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Perceptual hash for AI duplicate-photo detection (ai_services)",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("flagged", "Flagged"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_anomaly_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of flag codes raised by the verification-assist checks",
                    ),
                ),
                (
                    "ai_anomaly_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 (clean) - 1 (highly suspicious)",
                        max_digits=4,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_records",
                        to="agents.agent",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribution_records",
                        to="distributions.school",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["verification_status"],
                        name="distributio_verific_74a35a_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="distributio_timesta_4a8714_idx"
                    ),
                ],
            },
        ),
    ]
