# Generated by Django 5.2.15 on 2026-06-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionrecord',
            name='location_name',
            field=models.CharField(blank=True, help_text="Reverse-geocoded place name for gps_lat/gps_lng (e.g. 'Kumbungu, Northern Region'). Best-effort, set client-side at capture time -- coordinates remain the source of truth.", max_length=255),
        ),
    ]
