# Generated by Django 6.0.6 on 2026-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('momo_prompt', 'MTN MoMo Prompt'), ('hubtel_checkout', 'Card / Bank / Other MoMo (Hubtel)'), ('cash_on_delivery', 'Cash on Delivery')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('collect_on_delivery', 'Collect on Delivery')], default='pending', max_length=20),
        ),
    ]
